Dev
LaunchCodeEducation/intro-to-web-dev-curriculum pull request #32
Opened 2023-08-07 18:29 UTC by jwoolbright23

2023-08-07 20:12 UTC, icr8FreeCode requested changes
/introduction/ - should key terms be the terms used in the course related to the content on the entire book/chapter? 
- /introduction/reading/technologies-and-jobs/ Unit 1 Technologies 1. where should that link go? 
- /installs-and-setups/#setting-up-your-terminal unclear on what a terminal is then it links to/installations/terminal-setup/ where it talks about CLI, CLI needs to be explained and the difference between CLI vs Terminal 
- /how-programs-work/reading/installs-and-setups/ - Setting up GIT section points to a different installation file than terminal setup. is this intentional? 
- /how-programs-work/reading/your-first-program/#back-to-the-terminal the screen shots with `computer:js-hello-world username:` add confusion and should only include the command `git clone` or intended input/output
- Should Welcome be at the top of Chapter 3 ? 
- Should the starter code in Get the Starter Code match Section 1 Starter Code? 
- Do we care that the metadata has not been updated on candidate testing and Hello World, HTML Me Something?
- /installations/terminal-setup/ Terminal Setup is not the correct terminology here for Git installation. Windows terminal would be cmd Git is a version control tool that ran on the command line

2023-08-07 20:23 UTC, icr8FreeCode commented on content/how-programs-work/reading/images/Compiler.png
These images should be replaced by better images for these architecture design

2023-08-07 20:24 UTC, icr8FreeCode commented on content/how-programs-work/reading/images/Front-vs-back-end.png
This image is so not a good visual aid for learners in terms of the design icons. Please replace this with better images

2023-08-08 03:32 UTC, icr8FreeCode commented on content/installations/_index.md
inconsistent metadata

2023-08-08 03:32 UTC, icr8FreeCode commented on content/installations/install-git/_index.md
inconsistent metadata

2023-08-08 03:43 UTC, icr8FreeCode reviewed
There are a some inconsistencies in metadata for front-matter that should be addressed. We should remove the metadata attributes we don't need or add them to the missing files

2023-08-08 03:43 UTC, icr8FreeCode commented on content/installations/install-node/_index.md
inconsistent metadata

2023-08-08 03:43 UTC, icr8FreeCode commented on content/installations/install-visual-studio/_index.md
inconsistent metadata

2023-08-08 03:43 UTC, icr8FreeCode commented on content/installations/terminal-setup/_index.md
inconsistent metadata

2023-08-08 15:33 UTC, jwoolbright23 commented on content/how-programs-work/reading/images/Compiler.png
Will work with Rob to find a new image after merge so that we can move forward with merge.

2023-08-08 15:33 UTC, jwoolbright23 commented on content/how-programs-work/reading/images/Front-vs-back-end.png
Will work with Rob to find a new image after merge so that we can move forward with merge.

2023-08-08 16:10 UTC, merged