Chapter 19 terminal
LaunchCodeEducation/intro-to-web-dev-curriculum pull request #58
Opened 2023-09-21 14:50 UTC by jwoolbright23

2023-09-26 15:58 UTC, icr8FreeCode requested changes

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/locate_launchcode_courses.png.1
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/lc101_current_dir.png.3
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/lc101_current_dir.png.2
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/lc101_current_dir.png.1
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/init_tree.png.1
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/unit1_current_dir.png.1
not sure what this file is ?

2023-09-26 15:58 UTC, icr8FreeCode commented on content/appendices/terminal-commands/pictures/unit1_current_dir.png.2
not sure what this file is ?

2023-10-02 15:45 UTC, jwoolbright23 commented on content/appendices/terminal-commands/pictures/locate_launchcode_courses.png.1
Added directory structure within javascript-projects repo: https://github.com/LaunchCodeEducation/javascript-projects/tree/main/terminal-commands/launchcode_courses

This applies to this comment and all following.

2023-10-02 16:47 UTC, icr8FreeCode approved these changes

2023-10-03 14:14 UTC, merged